name: Build Verification

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle


      - name: Compile and verify framework
        run: ./gradlew clean assemble testClasses


      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            build/reports
            build/test-results


      - name: Telegram notification
        if: always()
        run: |
          STATUS="${{ job.status }}"

          if [ "$STATUS" = "success" ]; then
            ICON="✅"
          else
            ICON="❌"
          fi

          curl -s -X POST \
          "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
          --data-urlencode text="${ICON} Build Verification ${STATUS}"